services:
  mysql-server:
    image: mysql:8
    container_name: back_form_app
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=adminUser
      - MYSQL_DATABASE=back_form_app
    ports:
      - '3309:3306'
    networks:
      - net-mysql-server
    volumes:
      - data-mysql-volume:/var/lib/mysql

networks:
  net-mysql-server:


volumes:
  data-mysql-volume:
